### ISSUE TITLE
https://www.luckypatchers.com/baixar-lucky-patcher-apk/

### ISSUE THREAD

**Issue by Jcbrewster4180** [HemanthJabalpuri/Replace_KingRoot_with_SuperSU#4]
https://chrome.google.com/webstore Superuser LG su cmd superuser root kingroot/user/library

**Comment by Jcbrewster4180** [comment]
> https://chrome.google.com/webstore Superuser LG su cmd superuser root kingroot/user/library

- [ ] - []()@Jcbrewster4180 # # @HemanthJabalpuri ~~````

````~~

**Comment by HemanthJabalpuri** [comment]
what?
